### ISSUE TITLE
[Feature]: Support for PHP 7.0

### ISSUE THREAD

**Issue by MarcosRolando** [Unleash/unleash-client-php#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the new feature

Hello, first of all I wanted to say that I appreciate the work done for the Unleash community and all of the effort that went into this SDK. Now onto the issue, are there any plans to eventually support PHP 7.0? If not, are there any technical reasons for it (in case someone tries to add the support themselves)?

### Is your feature request related to a problem? (optional)

Currently unable to use this client for a project because of the PHP version (changing the project PHP version is unfortunately not possible)

**Comment by RikudouSage** [comment]
Hello, as far as I know, there are no plans to support it currently.

PHP 7.0 is not that widespread (5% or so) that's why we didn't do an analysis of what it would take to support it. We'll discuss it internally and let you know.

Basically what needs to be done is adding two more transpilation layers, to 7.1 and 7.0, checking that everything works, and rewriting all the tests to use 7.0 syntax only.

**Comment by MarcosRolando** [comment]
Thanks! Looking forward to your answer 😄

**Comment by diegosolo** [comment]
@RikudouSage, is there anything I can do to help? I was thinking on something based on [this PR](https://github.com/Unleash/unleash-client-php/pull/48/files), but I'm not sure what I'd be missing. I could work on something with a bit of orientation and reviewng. Let me know. Thanks!

**Comment by RikudouSage** [comment]
@MarcosRolando Sorry for the late reply. We've discussed it and decided 7.0 will not be officially supported, it doesn't get security updates anymore and it would be another version we have to support.

@diegosolo The only thing I can think of is manintaining a fork that supports php 7.0, you could add rectors for php 7.1 and 7.0 and check that everything works (the tests should help there), beware that tests need to be written with the syntax of the lowest supported version, so 7.0 in this case.
