### ISSUE TITLE
Bug: stub for EventDispatcher Interface error

### ISSUE THREAD

**Issue by angeloinqbyte** [Unleash/unleash-client-php#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We use laravel 5.6 with symfony/http-kernel:^4.0
When we run ` composer dumpautoload` this error is thrown:
```
Declaration of Unleash\Client\Helper\EventDispatcher::addListener(string $eventName, callable $listen
  er, int $priority = 0): void must be compatible with Symfony\Component\EventDispatcher\EventDispatche
  rInterface::addListener($eventName, $listener, $priority = 0)
```

### To reproduce

1. must use laravel 5.6
2. install unleash 1.7 (event dispatcher requirements not installed)
3. run composer dumpautoload

### Version

1.7.072

### Expected behavior

no errors since we wont be using the event dispatcher.

**Comment by FredrikOseberg** [comment]
@angeloinqbyte Thanks for the report. We'll look into this. @RikudouSage do you have some input on this issue?

**Comment by RikudouSage** [comment]
I'm currently on my vacation so I'll have a proper look when I return. It happens because event dispatcher is installed but it's way too old. I'll try to think of a solution next week.

**Comment by RikudouSage** [comment]
@angeloinqbyte @FredrikOseberg The conflicting helper event dispatcher has been deprecated and isn't used internally anymore, after the fix gets merged older Symfony event dispatcher shouldn't cause a problem.
