### ISSUE TITLE
Feat: When Client Registration Fails on init/build, allow to proceed and use Stale Cache if it exists

### ISSUE THREAD

**Issue by angeloinqbyte** [Unleash/unleash-client-php#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the new feature

It would be great if other HTTP requests fail, in our case when automatic client registration fails when initializing, Unleash wont stop and throw an error and instead allow us to proceed to use the stale cache if it exists.

### Is your feature request related to a problem? (optional)

the HTTP request for automatic client registration returns 4xx 5xx during unleash initialization, unleash itself throws an error and hard crashes our fflag service initialization that use unleash. We dont handle this error at the moment because we expected unleash to continue building itself then allow us to use the stale cache.

### Describe alternatives you've considered (optional)

I read we can turn off automatic client registration, would that help resolve the problem? what side effects would that have? or should we just accept and expect that when client registration happens to fail we just catch the error and handle it?

### Additional context (optional)

`Symfony\Component\HttpClient\Exception\TransportException: Empty reply from server for "https://app.unleash-hosted.com/nattier/api/client/register". in /home/forge/kryptonescort.com/vendor/symfony/http-client/Response/CurlResponse.php:334
Stack trace:
#0 /home/forge/kryptonescort.com/vendor/symfony/http-client/Response/TransportResponseTrait.php(174): Symfony\Component\HttpClient\Response\CurlResponse::perform(Object(Symfony\Component\HttpClient\Internal\CurlClientState), Array)
#1 /home/forge/kryptonescort.com/vendor/symfony/http-client/Response/CommonResponseTrait.php(153): Symfony\Component\HttpClient\Response\CurlResponse::stream(Array, NULL)
#2 /home/forge/kryptonescort.com/vendor/symfony/http-client/Response/TransportResponseTrait.php(53): Symfony\Component\HttpClient\Response\CurlResponse::initialize(Object(Symfony\Component\HttpClient\Response\CurlResponse))
#3 /home/forge/kryptonescort.com/vendor/symfony/http-client/Psr18Client.php(100): Symfony\Component\HttpClient\Response\CurlResponse->getStatusCode()
#4 /home/forge/kryptonescort.com/vendor/unleash/client/src/Client/DefaultRegistrationService.php(84): Symfony\Component\HttpClient\Psr18Client->sendRequest(Object(Nyholm\Psr7\Request))
#5 /home/forge/kryptonescort.com/vendor/unleash/client/src/DefaultUnleash.php(156): Unleash\Client\Client\DefaultRegistrationService->register(Array)
#6 /home/forge/kryptonescort.com/vendor/unleash/client/src/DefaultUnleash.php(66): Unleash\Client\DefaultUnleash->register()
#7 /home/forge/kryptonescort.com/vendor/unleash/client/src/UnleashBuilder.php(496): Unleash\Client\DefaultUnleash->__construct(Array, Object(Unleash\Client\Repository\DefaultUnleashRepository), Object(Unleash\Client\Client\DefaultRegistrationService), Object(Unleash\Client\Configuration\UnleashConfiguration), Object(Unleash\Client\Metrics\DefaultMetricsHandler), Object(Unleash\Client\Variant\DefaultVariantHandler))
#8 /home/forge/kryptonescort.com/app/Containers/Shared/Services/UnleashFeatureFlagService.php(70): Unleash\Client\UnleashBuilder->build()`

**Comment by RikudouSage** [comment]
Very sorry for the late reply. As a workaround you can indeed disable automatic registration and then register manually using `$unleash->register()` where you can catch the exception. This allows you to have a valid Unleash instance even if registration fails. I will be implementing a fix for this starting January.
