### ISSUE TITLE
Bug: Can't use temporary expression in write context

### ISSUE THREAD

**Issue by pure4499** [Unleash/unleash-client-php#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/Unleash/unleash-client-php/blob/v2.4.183/src/Unleash.php#L10

This change started erroring out. "Can't use temporary expression in write context"

data type should be removed from const.

### Version

v2.4.183

### Expected behavior

data type should be removed from const.

**Comment by RikudouSage** [comment]
It seems like your build system uses a newer version of php than your servers. Please make sure that you're installing the package on the php version that will actually run the code.

**Comment by RikudouSage** [comment]
@pure4499 Has that solved your issue? Please let me know, otherwise I'll be closing the issue soon.

**Comment by RikudouSage** [comment]
Haven't gotten any response, closing.
