### ISSUE TITLE
Feat: method `->withTimeout(secs)`

### ISSUE THREAD

**Issue by aagjalpankaj** [Unleash/unleash-client-php#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the new feature

Sometimes our self-hosted gitlab is unreachable due to some maintenance activities. In that case, it takes more than 1 min to return the cached value or the default value. Can we add method `->withTimeout(secs)`?

### Is your feature request related to a problem? (optional)

Sometimes our self-hosted gitlab is unreachable due to some maintenance activities. In that case, it takes more than 1 min to return the cached value or the default value.

### Describe alternatives you've considered (optional)

set_time_limit

**Comment by RikudouSage** [comment]
There's no unified way to set a timeout for the PSR http client abstraction (at least I don't know of any), that needs to be done in the http client you use.

For guzzle you can do it like this:

```php
    $httpClient = new Client([
        RequestOptions::TIMEOUT => 2,
    ]);
```

For Symfony like this:

```php
    $httpClient = HttpClient::create([
        'timeout' => 2,
    ]);
    $httpClient = new Psr18Client($httpClient);
```

If you use a different http client, there's probably a way to set a default timeout.

Then you do it like this:

```php
$unleash = UnleashBuilder::create()
    ->withAppName($appName)
    ->withAppUrl($appUrl)
    ->withInstanceId($instanceId)
    ->withHttpClient($httpClient) // <-- this is the important part
    ->build()
;
```

**Comment by RikudouSage** [comment]
I've added it as an example in #221
