### ISSUE TITLE
[Bug]: 1.3.172 php7.2 compatibility issue for AbstractListOperatorValidator

### ISSUE THREAD

**Issue by angeloinqbyte** [Unleash/unleash-client-php#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

src/ConstraintValidator/Operator/Lists/AbstractListOperatorValidator.php uses array_is_list which is a php 8 function which causes an exception to be thrown when running php 7.2 based code.

### To reproduce

Execute the isEnabled Function in a Php 7.2 environment.

### Version

1.3.172

### Expected behavior

shoulde not throw an error. Currently works fine on 1.2.572

**Comment by RikudouSage** [comment]
Fixed in 1.3.272, thanks for the report.
