### ISSUE TITLE
[Bug]: symfony/event-dispatcher is required

### ISSUE THREAD

**Issue by netzhuffle** [Unleash/unleash-client-php#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Latest release added symfony/event-dispatcher as an optional dependency (according to composer.json, it is only required for dev).

Yet the code is written in a way that symfony/event-dispatcher is required. Thus an exception is triggered when e.g. a feature flag is disabled and the autoloader cannot find the associated classes, e.g. Symfony\Contracts\EventDispatcher\Event.

### To reproduce

1. Run Unleash without sentry/event-dispatcher
2. Check for a disabled feature flag

### Version

v1.5.081

### Expected behavior

`isEnabled()` returns `false` instead of throwing an error or exception.

**Comment by RikudouSage** [comment]
Fixed in `1.5.181`. Let me know if it works.

**Comment by netzhuffle** [comment]
Yes, can confirm it worked. Thanks!
